#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Jun 08 21:41:04 +0800 2025
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_8 zynq_ultra_ps_e_vip_v1_0_8 xil_defaultlib axi_lite_ipif_v3_0_4 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_uartlite_v2_0_26 dist_mem_gen_v8_0_13 fifo_generator_v13_2_5 lib_fifo_v1_0_14 interrupt_control_v3_1_4 axi_quad_spi_v3_2_21 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 proc_sys_reset_v5_0_13 gtwizard_ultrascale_v1_7_9 axi_iic_v2_0_25 xlslice_v1_0_2 xlconcat_v2_1_4 xlconstant_v1_1_7 axi_protocol_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_26 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/5edb/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_uartlite_0_0/sim/design_1_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_21 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/63ec/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_quad_spi_0_0/sim/design_1_axi_quad_spi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_block.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_por_fsm_top.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_bgt_fsm.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_device_rom.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_por_fsm.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_tile_config.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_constants_config.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_arbiter.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_arbiter_adc.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_register_decode.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_address_decoder.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_axi_lite_ipif.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_counter_f.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_pselect_f.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_slave_attachment.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_rf_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_control_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_control.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_access_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_irq_req_ack.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_irq_sync.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0bufg_gt_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_overvol_irq.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_powerup_state_irq.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_sysref_count.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_mrk_count.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_data_align.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_fifo_ctrl.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_rst_cnt.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_clk_detection.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0.v" \
    "$ref_dir/../../../bd/design_1/ipshared/d37a/AXI_Lite.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_AXI_Lite_0_0/sim/design_1_AXI_Lite_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_99M_0/sim/design_1_rst_ps8_0_99M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_DAC_Data_Gen_0_0/sim/design_1_DAC_Data_Gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d12e/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/ip_0/sim/gtwizard_ultrascale_v1_7_gtye4_channel.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/ip_0/sim/design_1_aurora_64b66b_0_3_gt_gtye4_channel_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/ip_0/sim/design_1_aurora_64b66b_0_3_gt_gtwizard_gtye4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/ip_0/sim/design_1_aurora_64b66b_0_3_gt_gtwizard_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/ip_0/sim/design_1_aurora_64b66b_0_3_gt.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_support.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/example_design/gtwizard_ultrascale_v1_7_gtye4_common.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/example_design/design_1_aurora_64b66b_0_3_gt_gtye4_common_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_gt_common_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_support_reset_logic.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_ultrascale_tx_userclk.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_clock_module.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/example_design/design_1_aurora_64b66b_0_3_axi_to_drp.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/example_design/gt/design_1_aurora_64b66b_0_3_multi_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/example_design/gt/design_1_aurora_64b66b_0_3_ultrascale_rx_userclk.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_standard_cc_module.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_reset_logic.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_cdc_sync.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3_core.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_polarity_check.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/example_design/gt/design_1_aurora_64b66b_0_3_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_64b66b_scrambler.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_sym_gen.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_aurora_lane_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_channel_err_detect_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_channel_init_sm_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_ch_bond_code_gen_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_err_detect_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_global_logic_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_lane_init_sm_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_ll_control_sm_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_ll_datapath_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3/src/design_1_aurora_64b66b_0_3_tx_ll_simplex.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_aurora_64b66b_0_3/design_1_aurora_64b66b_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_iic_v2_0_25 $vhdlan_opts \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1529/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_iic_0_0/sim/design_1_axi_iic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_0/sim/design_1_xlslice_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_1/sim/design_1_xlslice_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_2/sim/design_1_xlslice_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_4_1/sim/design_1_xlslice_4_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_6_0/sim/design_1_xlslice_6_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_7_0/sim/design_1_xlslice_7_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_8_0/sim/design_1_xlslice_8_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_8_1/sim/design_1_xlslice_8_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_10_0/sim/design_1_xlslice_10_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_11_0/sim/design_1_xlslice_11_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_0_1/sim/design_1_proc_sys_reset_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_0_3/sim/design_1_proc_sys_reset_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Data_Link_Vio_0_0/sim/design_1_Data_Link_Vio_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_6_1/sim/design_1_xlslice_6_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_13_0/sim/design_1_xlslice_13_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_13_1/sim/design_1_xlslice_13_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_14_0/sim/design_1_xlslice_14_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_15_0/sim/design_1_xlslice_15_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_16_0/sim/design_1_xlslice_16_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_17_0/sim/design_1_xlslice_17_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_18_0/sim/design_1_xlslice_18_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_19_0/sim/design_1_xlslice_19_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_20_0/sim/design_1_xlslice_20_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_15_1/sim/design_1_xlslice_15_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_16_1/sim/design_1_xlslice_16_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_17_1/sim/design_1_xlslice_17_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_18_1/sim/design_1_xlslice_18_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_19_1/sim/design_1_xlslice_19_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_20_1/sim/design_1_xlslice_20_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_21_0/sim/design_1_xlslice_21_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_22_0/sim/design_1_xlslice_22_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_12_1/sim/design_1_xlslice_12_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_uartlite_0_1/sim/design_1_axi_uartlite_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_6_2/sim/design_1_xlslice_6_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_32_0/sim/design_1_xlslice_32_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_33_0/sim/design_1_xlslice_33_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_1_0/sim/design_1_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_2/sim/design_1_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_2_0/sim/design_1_xlconcat_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_23_0/sim/design_1_xlslice_23_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_23_1/sim/design_1_xlslice_23_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_23_2/sim/design_1_xlslice_23_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_23_3/sim/design_1_xlslice_23_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_38_2/sim/design_1_xlslice_38_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_3_0/sim/design_1_xlconcat_3_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_35_0/sim/design_1_xlslice_35_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_41_0/sim/design_1_xlslice_41_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_41_1/sim/design_1_xlslice_41_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_41_2/sim/design_1_xlslice_41_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_41_3/sim/design_1_xlslice_41_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_3_1/sim/design_1_xlconcat_3_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_3/sim/design_1_xlconstant_0_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_32_1/sim/design_1_xlslice_32_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_32_2/sim/design_1_xlslice_32_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_5/sim/design_1_xlconstant_0_5.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_40_0/sim/design_1_xlslice_40_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_uartlite_2_0/sim/design_1_axi_uartlite_2_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_iic_1_0/sim/design_1_axi_iic_1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_uartlite_3_0/sim/design_1_axi_uartlite_3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_CPF_Check_0_0/sim/design_1_CPF_Check_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Aurora_Init_Rstn_0_1/sim/design_1_Aurora_Init_Rstn_0_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_LVDS_Rx_0_0/sim/design_1_LVDS_Rx_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_AXI_Stream_MUX_0_5/sim/design_1_AXI_Stream_MUX_0_5.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_LVDS_Tx_0_0/sim/design_1_LVDS_Tx_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MTS_Clk_0_0/sim/design_1_MTS_Clk_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_BUFG_MMCM_OUT_0_0/sim/design_1_BUFG_MMCM_OUT_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_33_1/sim/design_1_xlslice_33_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_49_0/sim/design_1_xlslice_49_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_2_1/sim/design_1_xlconcat_2_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_Down_Sampling_0_0/sim/design_1_Down_Sampling_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_33_2/sim/design_1_xlslice_33_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/sim/bd_f60c_ila_lib_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/bd_0/sim/bd_f60c.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_0_0/sim/design_1_system_ila_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_1_0/bd_0/ip/ip_0/sim/bd_365d_ila_lib_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_1_0/bd_0/sim/bd_365d.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_1_0/sim/design_1_system_ila_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_2_0/bd_0/ip/ip_0/sim/bd_36ad_ila_lib_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_2_0/bd_0/sim/bd_36ad.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_2_0/sim/design_1_system_ila_2_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_3_0/bd_0/ip/ip_0/sim/bd_f6fc_ila_lib_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_3_0/bd_0/sim/bd_f6fc.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_system_ila_3_0/sim/design_1_system_ila_3_0.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/d0f7" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../FPGA_Firmware.gen/sources_1/bd/design_1/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
